name: Test

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3. Selenoid
      - name: Start Selenoid
        uses: Xotabu4/selenoid-github-action@v2

      # 4. Gradle + тесты
      - name: Run tests
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      # 5. Проверка результатов (очень важно)
      - name: Debug files
        if: always()
        run: ls -R build

      # 6. История (если есть)
      - name: Checkout gh-pages history
        if: always()
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      # 7. Allure report
      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@v1.8
        with:
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      # 8. Деплой
      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history